#!/usr/bin/env bun
// Generates src/cli-assets.ts with embedded binary assets for the compiled CLI binary.
// Run: bun scripts/generate-cli-assets.ts

import { readFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");

async function readAsBase64(path: string): Promise<string> {
  const buf = await readFile(path);
  return buf.toString("base64");
}

const pgliteDir = join(root, "node_modules/@electric-sql/pglite/dist");
const postgrestDir = join(root, "node_modules/postgrest-parser/pkg");

console.log("Reading assets...");
const [pgliteWasm, pgliteData, pgcrypto, uuidOssp, postgrestWasm] = await Promise.all([
  readAsBase64(join(pgliteDir, "pglite.wasm")),
  readAsBase64(join(pgliteDir, "pglite.data")),
  readAsBase64(join(pgliteDir, "pgcrypto.tar.gz")),
  readAsBase64(join(pgliteDir, "uuid-ossp.tar.gz")),
  readAsBase64(join(postgrestDir, "postgrest_parser_bg.wasm")),
]);

console.log("Generating src/cli-assets.ts...");

const output = `// AUTO-GENERATED by scripts/generate-cli-assets.ts — do not edit manually.
// Run: bun scripts/generate-cli-assets.ts

function b64(s: string): Uint8Array {
  return new Uint8Array(Buffer.from(s, "base64"));
}

export const pgliteWasm = b64("${pgliteWasm}");
export const pgliteData = b64("${pgliteData}");
export const pgcryptoBundle = b64("${pgcrypto}");
export const uuidOsspBundle = b64("${uuidOssp}");
export const postgrestWasm = b64("${postgrestWasm}");
`;

await Bun.write(join(root, "src/cli-assets.ts"), output);
console.log("Done.");
